### ISSUE TITLE
The data files are not installed with pip install.

### ISSUE THREAD

**Issue by df-seagate** [the-lay/py-friendly-words#1]
Once I created the data directory and copied the files I got an error about an index out of range.
When running
    fw.preload()
    friendly_token = fw.generate('po', separator='-')

I had to modify the generate method:
chosen_word = random.randrange(0, self.WORD_LISTS[c]['n']))
  to
chosen_word = random.randrange(0, len(self.WORD_LISTS[c]['list']))

**Comment by the-lay** [comment]
Ah, thanks so much for bringing this up! I didn't touch this project for a long time!

1. I've forgot to include data files, you are right!

2. I've replaced chosen word generation to `chosen_word = random.randint(0, self.WORD_LISTS[c]['n'] - 1)`. That should be better. Can't remember why I picked `randrange` instead of randint :thinking: 

3. I've added tests to make sure that wouldn't happen ever again and added github actions to make sure I don't break anything in the future.

Please let me know if the most recent version (1.1.2) works for you now.
